<script type="text/javascript">
document.body.style.background = "#ffffff";
document.getElementById('jwarp').style.background='#ffffff';
</script>
<style type="text/css">
	*{text-align: justify;}
</style>

<div class="chap">
<h1>  <span>Wie </span></h1>
<img src="<?php echo HTTPPATH.$config['image'];?>ieee_wie_purple.jpg"  style='display: inline-block;float: right;width: 30%;min-width:150px;margin: 0 5%;' alt="wie">


		<p>THE WIE AFFINITY GROUP OF OUR COLLEGE WAS STARTED IN THE YEAR 2011. WITH ONLY FEW MEMBERS IN THE BEGININNG,OUR AFFINITY GROUP HAS WITNESSED A REMARKABLE PROGRESS IN NEMBERS OVER THESE YEARS.OUR AFFINITY GROUP COMMUNICATE WITH ITS MEMBERS BY CONDUCTING MEETINGS ONCE IN EVERY WEEK (USUALLY ON FRIDAYS). WE ALSO CONDUCT TALKS AND SEMINARS ON IEEE SPECTRUM MAGAZINE EVERY WEEK FOR THE WIE MEMBERS TO IMPROVE THEIR TECHNICAL KNOW-HOW AND TO UPDATE THEM WITH THE LATEST TECHNOLOGY.</p>
<p>&nbsp;</p>
<p>OUR STUDENTS’ BRANCH HAS CONDUCTED ACTIVITIES NOT ONLY FOR OUR MEMBERS BUT ALSO FOR SCHOOL STUDENTS AND EVEN THEIR TEACHERS.WE HAD A ONE DAY PROGRAM “WIESTAR” IN OUR COLLEGE TO PROVIDE ASSISTANCE TO SCHOOL TEACHERS ABOUT BASIC ELECTRONICS, CIRCUIT DEBUGGING AND OTHER ELECTRONICS RELATED TOPICS WHICH HAVE REALLY HELPED THEM IN IMPROVING THEIR KNOWLEDGE APART FROM THEIR ACADEMICS ABOUT ENGINEERING AND VARIOUS RELATED FIELDS. IN ANOTHER PROGRAM CONDUCTED BY OUR SB, “ABHIGYAAN”, WE HAVE CONDUCTED A ONE DAY AWARENESS PROGRAM, FOR THE STUDENTS IN A GIRLS HIGH SCHOOL ABOUT ENGINEERING AND MADE THEM TO DO SCIENCE ACTIVITIES FOR A BETTER UNDERSTANDING ABOUT THEIR SUBJECTS .OUR STUDENTS BRANCH HAS ALWAYS STOOD FOR UPLIFTING YOUNGER WOMEN , TO MAKE THEM FEEL CONFIDENT ENOUGH  AND TO BRING THEM INTO THE LIGHT OF TECHNOLOGY . OUR WIE GROUP HAS EVEN STOOD FOR A SOCIAL CAUSE. WE WIE MEMBERS WENT TO A GIRLS ORPHANAGE AND SPENT A WHOLE DAY WITH THEM. PROBABLY THAT WAS THE BEST EVER THING OUR SMALL IEEE STUDENT BANCH COULD DO TO THE SOCIETY. TO MAKE THOSE CHILDREN FEEL THAT THEY ARE INDEED PRIVILEGED THAN ANYONE ELSE IN THIS WORLD, TO LISTEN TO WHAT THEIR LITTLE MINDS SPEAK OUT, TO GIVE THEM THE BEST OF OUR KNOWLEDGE ABOUT INFORMATION TECHNOLOGY, TO GIVE THEM HOPE . THIS TURNED OUT TO BE THE BEST DAY OF OUR LIVES. APART FROM THIS WE HAVE ALSO CONDUCTED SEMINARS AND WORKSHOPS FOR WIE MEMBERS ABOUT THE LATEST PREVAILING TOPICS.WE HOPE TO CONDUCT MORE EVENTS IN THIS ACADEMIC YEAR INCLUDING AN INTER COLLEGE EVENT , AEROSPACE AND AEROMODELLING WORKSHOP.</p>
<p id="ieeesight">&nbsp;</p><!--
<h1>  <span>SIGHT  SCTCE</span></h1>-->
<img style='width: 90%;margin: 0 auto;display: block;' src="<?php echo HTTPPATH.$config['image'];?>sight.png" alt="sight">
<div dir="ltr" style="text-align: left;" trbidi="on">
<h2 class="bullet" style="background: url(http://www.ieee.org/ieee/groups/webassets/@ieee/@web/@org/documents/images/gen-bullet-lg.gif) 0% 0% no-repeat rgb(255, 255, 255); border-bottom-color: rgb(224, 236, 247); border-bottom-style: solid; border-width: 0px 0px 2px; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 18px; line-height: 23.3999996185303px; margin: 0px 0px 10px; padding: 0px 0px 9px 13px;">
Objectives of SIGHT</h2>
<div style="background-color: white; border: 0px; color: #333333; font-family: Verdana, Arial, Helvetica, sans-serif; margin: 0px; padding: 0px;">
<div style="border-image-outset: initial; border-image-repeat: initial; border-image-slice: initial; border-image-source: initial; border-image-width: initial; border: 0px; font-size: 13.1999998092651px; line-height: 17.1599998474121px; padding: 0px 0px 10px;">
To promote the mission of IEEE regarding humanitarian technology activities, particularly:</div>
<ul style="border-image-outset: initial; border-image-repeat: initial; border-image-slice: initial; border-image-source: initial; border-image-width: initial; border: 0px; font-size: 12px; line-height: 18px; margin: 0px; padding: 0px 0px 10px;">
<li style="background: url(http://www.ieee.org/ieee/groups/webassets/@ieee/@web/@org/documents/images/gen-bullet.gif) 0% 3px no-repeat; border: 0px; font-size: 13.1999998092651px; line-height: 17.1599998474121px; list-style: none; margin: 0px; padding: 0px 0px 3px 15px; vertical-align: top;">To bring together members/IEEE OUs working in or wishing to work in humanitarian fields and to encourage and promote them in activities that use humanitarian technologies by giving them an opportunity for participation.</li>
<li style="background: url(http://www.ieee.org/ieee/groups/webassets/@ieee/@web/@org/documents/images/gen-bullet.gif) 0% 3px no-repeat; border: 0px; font-size: 13.1999998092651px; line-height: 17.1599998474121px; list-style: none; margin: 0px; padding: 0px 0px 3px 15px; vertical-align: top;">Increasing awareness of IEEE members and engineers of the potential of their work to improve the standard of living of underserved populations, and encouraging them to increase efforts in this direction.</li>
<li style="background: url(http://www.ieee.org/ieee/groups/webassets/@ieee/@web/@org/documents/images/gen-bullet.gif) 0% 3px no-repeat; border: 0px; font-size: 13.1999998092651px; line-height: 17.1599998474121px; list-style: none; margin: 0px; padding: 0px 0px 3px 15px; vertical-align: top;">To engage with NGOs, Civil Society Organizations, UN Organizations, Corporates, and other similar bodies to synergize efforts in delivering useful and sustainable technologies in their operations.</li>
<li style="background: url(http://www.ieee.org/ieee/groups/webassets/@ieee/@web/@org/documents/images/gen-bullet.gif) 0% 3px no-repeat; border: 0px; font-size: 13.1999998092651px; line-height: 17.1599998474121px; list-style: none; margin: 0px; padding: 0px 0px 3px 15px; vertical-align: top;">To work with other bodies in the global engineering community who have similar goals and help each other in delivering to the ideals and participate in joint activities like&nbsp;<a href="https://www.engineeringforchange.org/" style="color: purple; cursor: pointer; text-decoration: none;" target="">Engineering for Change (E4C)</a>.</li>
</ul>
<div>
<h2 class="bullet" style="background-attachment: initial; background-clip: initial; background-image: url(http://www.ieee.org/ieee/groups/webassets/@ieee/@web/@org/documents/images/gen-bullet-lg.gif); background-origin: initial; background-position: 0% 0%; background-repeat: no-repeat; background-size: initial; border-bottom-color: rgb(224, 236, 247); border-bottom-style: solid; border-width: 0px 0px 2px; color: black; font-size: 18px; line-height: 23.3999996185303px; margin: 0px 0px 10px; padding: 0px 0px 9px 13px;">
Prerequisites to form a SIGHT</h2>
<div style="border: 0px; margin: 0px; padding: 0px;">
<div style="border-image-outset: initial; border-image-repeat: initial; border-image-slice: initial; border-image-source: initial; border-image-width: initial; border: 0px; font-size: 12px; line-height: 18px; margin: 0px; padding: 0px;">
Six or more IEEE members in good standing and passionate in humanitarian technology activities centered on one or more above interest areas.&nbsp;Members must be affiliated to Section or Student branch.&nbsp;For Sections, at least three of those signatories must be representatives from two different chapters.<br /><br />The prospective SIGHT will need to have an affiliation to a section or student branch only. The prospective SIGHT will need to submit an application requesting formation of a SIGHT.<br /><br /><strong>Application:</strong><br /><br />If you are interested in forming a SIGHT group, you may apply by completing the&nbsp;<a href="http://www.ieee.org/about/corporate/ad_hoc/sight_group_formation_2013.pdf" style="color: purple; cursor: pointer; text-decoration: none;" target="_blank">petition</a>&nbsp;(PDF, 267 KB) and submitting the application materials to the SIGHT Steering Committee for review via:</div>
<div style="border-image-outset: initial; border-image-repeat: initial; border-image-slice: initial; border-image-source: initial; border-image-width: initial; border: 0px; font-size: 13.1999998092651px; line-height: 17.1599998474121px; padding: 0px 0px 10px;">
<strong>E-mail:</strong>&nbsp;<a href="mailto:h.s.brown@ieee.org" style="color: purple; cursor: pointer; text-decoration: none;" target="">Holly Schneider Brown</a>&nbsp;(e-mail preferred method)<br /><strong>Fax:</strong>&nbsp;+1 732 463 3657<br /><strong>Mail:</strong>&nbsp;SIGHT Steering Committee<br />445 Hoes Lane<br />Piscataway, NJ 08854-4141<br />USA</div>
<div style="border-image-outset: initial; border-image-repeat: initial; border-image-slice: initial; border-image-source: initial; border-image-width: initial; border: 0px; font-size: 13.1999998092651px; line-height: 17.1599998474121px; padding: 0px 0px 10px;">
<br /></div>
<h2 class="bullet" style="background-attachment: initial; background-clip: initial; background-image: url(http://www.ieee.org/ieee/groups/webassets/@ieee/@web/@org/documents/images/gen-bullet-lg.gif); background-origin: initial; background-position: 0% 0%; background-repeat: no-repeat; background-size: initial; border-bottom-color: rgb(224, 236, 247); border-bottom-style: solid; border-width: 0px 0px 2px; color: black; font-size: 18px; line-height: 23.3999996185303px; margin: 0px 0px 10px; padding: 0px 0px 9px 13px;">
Seed grants</h2>
<div style="border-image-outset: initial; border-image-repeat: initial; border-image-slice: initial; border-image-source: initial; border-image-width: initial; border: 0px; margin: 0px; padding: 0px;">
<div style="border-image-outset: initial; border-image-repeat: initial; border-image-slice: initial; border-image-source: initial; border-image-width: initial; border: 0px; font-size: 13.1999998092651px; line-height: 17.1599998474121px; padding: 0px 0px 10px;">
To help set IEEE SIGHT Group activities in motion, the Humanitarian Ad Hoc Committee has decided to award initial seed grants of US$250 to each of the first 50 SIGHT Groups formed.<br /><br />If you are interested in forming a SIGHT Group, complete the petition as soon as possible to qualify for US$250 that will aid in kicking off your SIGHT Group's ideas and activities.</div>
<div style="border-image-outset: initial; border-image-repeat: initial; border-image-slice: initial; border-image-source: initial; border-image-width: initial; border: 0px; font-size: 13.1999998092651px; line-height: 17.1599998474121px; padding: 0px 0px 10px;">
<br /></div>
<h2 class="bullet" style="background-attachment: initial; background-clip: initial; background-image: url(http://www.ieee.org/ieee/groups/webassets/@ieee/@web/@org/documents/images/gen-bullet-lg.gif); background-origin: initial; background-position: 0% 0%; background-repeat: no-repeat; background-size: initial; border-bottom-color: rgb(224, 236, 247); border-bottom-style: solid; border-width: 0px 0px 2px; color: black; font-size: 18px; line-height: 23.3999996185303px; margin: 0px 0px 10px; padding: 0px 0px 9px 13px;">
SIGHT Steering Committee</h2>
<div style="border-image-outset: initial; border-image-repeat: initial; border-image-slice: initial; border-image-source: initial; border-image-width: initial; border: 0px; margin: 0px; padding: 0px;">
<div style="border-image-outset: initial; border-image-repeat: initial; border-image-slice: initial; border-image-source: initial; border-image-width: initial; border: 0px; font-size: 13.1999998092651px; line-height: 17.1599998474121px; padding: 0px 0px 10px;">
</div>
<ul style="border-image-outset: initial; border-image-repeat: initial; border-image-slice: initial; border-image-source: initial; border-image-width: initial; border: 0px; font-size: 12px; line-height: 18px; margin: 0px; padding: 0px 0px 10px;">
<li style="background: url(http://www.ieee.org/ieee/groups/webassets/@ieee/@web/@org/documents/images/gen-bullet.gif) 0% 3px no-repeat; border: 0px; font-size: 13.1999998092651px; line-height: 17.1599998474121px; list-style: none; margin: 0px; padding: 0px 0px 3px 15px; vertical-align: top;">Kartik Kulkarni (Chair)</li>
<li style="background: url(http://www.ieee.org/ieee/groups/webassets/@ieee/@web/@org/documents/images/gen-bullet.gif) 0% 3px no-repeat; border: 0px; font-size: 13.1999998092651px; line-height: 17.1599998474121px; list-style: none; margin: 0px; padding: 0px 0px 3px 15px; vertical-align: top;">Ed Aoki</li>
<li style="background: url(http://www.ieee.org/ieee/groups/webassets/@ieee/@web/@org/documents/images/gen-bullet.gif) 0% 3px no-repeat; border: 0px; font-size: 13.1999998092651px; line-height: 17.1599998474121px; list-style: none; margin: 0px; padding: 0px 0px 3px 15px; vertical-align: top;">Alfredo Herrera (Engagement Subcommittee Chair)</li>
<li style="background: url(http://www.ieee.org/ieee/groups/webassets/@ieee/@web/@org/documents/images/gen-bullet.gif) 0% 3px no-repeat; border: 0px; font-size: 13.1999998092651px; line-height: 17.1599998474121px; list-style: none; margin: 0px; padding: 0px 0px 3px 15px; vertical-align: top;">Nirupama Prakash Kumar</li>
<li style="background: url(http://www.ieee.org/ieee/groups/webassets/@ieee/@web/@org/documents/images/gen-bullet.gif) 0% 3px no-repeat; border: 0px; font-size: 13.1999998092651px; line-height: 17.1599998474121px; list-style: none; margin: 0px; padding: 0px 0px 3px 15px; vertical-align: top;">Ray Larsen (Projects Subcommittee Chair)</li>
<li style="background: url(http://www.ieee.org/ieee/groups/webassets/@ieee/@web/@org/documents/images/gen-bullet.gif) 0% 3px no-repeat; border: 0px; font-size: 13.1999998092651px; line-height: 17.1599998474121px; list-style: none; margin: 0px; padding: 0px 0px 3px 15px; vertical-align: top;">Raj Madhavan</li>
<li style="background: url(http://www.ieee.org/ieee/groups/webassets/@ieee/@web/@org/documents/images/gen-bullet.gif) 0% 3px no-repeat; border: 0px; font-size: 13.1999998092651px; line-height: 17.1599998474121px; list-style: none; margin: 0px; padding: 0px 0px 3px 15px; vertical-align: top;">Deepak Mathur (Operations Subcommittee Chair)</li>
<li style="background: url(http://www.ieee.org/ieee/groups/webassets/@ieee/@web/@org/documents/images/gen-bullet.gif) 0% 3px no-repeat; border: 0px; font-size: 13.1999998092651px; line-height: 17.1599998474121px; list-style: none; margin: 0px; padding: 0px 0px 3px 15px; vertical-align: top;">Eduardo Navarro</li>
<li style="background: url(http://www.ieee.org/ieee/groups/webassets/@ieee/@web/@org/documents/images/gen-bullet.gif) 0% 3px no-repeat; border: 0px; font-size: 13.1999998092651px; line-height: 17.1599998474121px; list-style: none; margin: 0px; padding: 0px 0px 3px 15px; vertical-align: top;">Jay Pearlman</li>
<li style="background: url(http://www.ieee.org/ieee/groups/webassets/@ieee/@web/@org/documents/images/gen-bullet.gif) 0% 3px no-repeat; border: 0px; font-size: 13.1999998092651px; line-height: 17.1599998474121px; list-style: none; margin: 0px; padding: 0px 0px 3px 15px; vertical-align: top;">Arjun Pillai</li>
<li style="background: url(http://www.ieee.org/ieee/groups/webassets/@ieee/@web/@org/documents/images/gen-bullet.gif) 0% 3px no-repeat; border: 0px; font-size: 13.1999998092651px; line-height: 17.1599998474121px; list-style: none; margin: 0px; padding: 0px 0px 3px 15px; vertical-align: top;">Sampathkumar Veeraraghavan</li>
<li style="background: url(http://www.ieee.org/ieee/groups/webassets/@ieee/@web/@org/documents/images/gen-bullet.gif) 0% 3px no-repeat; border: 0px; font-size: 13.1999998092651px; line-height: 17.1599998474121px; list-style: none; margin: 0px; padding: 0px 0px 3px 15px; vertical-align: top;">Prasanna Venkatesan</li>
<li style="background: url(http://www.ieee.org/ieee/groups/webassets/@ieee/@web/@org/documents/images/gen-bullet.gif) 0% 3px no-repeat; border: 0px; font-size: 13.1999998092651px; line-height: 17.1599998474121px; list-style: none; margin: 0px; padding: 0px 0px 3px 15px; vertical-align: top;">Holly Schneider Brown (Staff Lead)</li>
</ul>
<div>
<h2 class="bullet" style="background-attachment: initial; background-clip: initial; background-image: url(http://www.ieee.org/ieee/groups/webassets/@ieee/@web/@org/documents/images/gen-bullet-lg.gif); background-origin: initial; background-position: 0% 0%; background-repeat: no-repeat; background-size: initial; border-bottom-color: rgb(224, 236, 247); border-bottom-style: solid; border-width: 0px 0px 2px; color: black; font-size: 18px; line-height: 23.3999996185303px; margin: 0px 0px 10px; padding: 0px 0px 9px 13px;">
SIGHT resources</h2>
<div style="border: 0px; font-size: 12px; line-height: 18px; margin: 0px; padding: 0px;">
<ul style="border: 0px; margin: 0px; padding: 0px 0px 10px;">
<li style="background: url(http://www.ieee.org/ieee/groups/webassets/@ieee/@web/@org/documents/images/gen-bullet.gif) 0% 3px no-repeat; border: 0px; font-size: 13.1999998092651px; line-height: 17.1599998474121px; list-style: none; margin: 0px; padding: 0px 0px 3px 15px; vertical-align: top;">The&nbsp;<a href="http://engineeringforchange-webinars.org/" style="color: purple; cursor: pointer; text-decoration: none;" target="">Engineering for Change Webinar Series</a>&nbsp;promotes emerging ideas in engineering for global development and connects you with a passionate community of practitioners who are leading the way to a better quality of life around the world. Every seminar will expand your knowledge and demonstrate how technology-based solutions are addressing real-world issues in underserved communities. Attendance is easy and FREE.</li>
<li style="background: url(http://www.ieee.org/ieee/groups/webassets/@ieee/@web/@org/documents/images/gen-bullet.gif) 0% 3px no-repeat; border: 0px; font-size: 13.1999998092651px; line-height: 17.1599998474121px; list-style: none; margin: 0px; padding: 0px 0px 3px 15px; vertical-align: top;"><a href="https://www.engineeringforchange.org/" style="color: purple; cursor: pointer; text-decoration: none;" target="">Engineering for Change</a>&nbsp;provides a forum to connect, collaborate, solve challenges, and share knowledge among a growing community of engineers, technologists, social scientists, NGOs, local governments, and community advocates, who are dedicated to improving the quality of life all over the world.</li>
</ul>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div> 


</div>